Add a no change contig name parameter in dotplot (#158)
* use abspath instead of relative path

* Fix a unicode problem in Python2.7

  File "/opt/biosoft/JCVI-github/lib/python2.7/site-packages/jcvi/compara/blastfilter.py", line 93, in blastfilter_main
    b.query, b.subject = key
TypeError: Argument 'val' has incorrect type (expected str, got unicode)

* add new parameter which will not change the contig name in plotting